import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navegation from './components/Navegation'
import 'bootstrap/dist/css/bootstrap.min.css';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>my app with next</title>
      </head>
      <body>
        <header>
          <Navegation />
        </header>
        {children}
      </body>
    </html>
  )
}
