import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const links = [{ label: "Home", route: "/" }, { label: "Page", route: "/about" }]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>my app with next</title>
      </head>
      <body>
        <header>
          {links.map(({ label, route }) => (
            <li key={route}>
              <Link href={route}>{label}</Link>
            </li>
          ))}
        </header>
        {children} </body>
    </html>
  )
}
